# Generated by Django 5.2 on 2025-08-02 11:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friendshiprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshiprequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='message',
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SongPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('spotify_track_id', models.CharField(blank=True, max_length=255, null=True)),
                ('spotify_track_url', models.URLField(blank=True, max_length=500, null=True)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('posted_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date', '-created_at'],
                'unique_together': {('user', 'posted_date')},
            },
        ),
    ]
