# Generated by Django 5.2.4 on 2025-08-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_friendshiprequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, help_text='Current consecutive days of posting'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_post_date',
            field=models.DateField(blank=True, help_text='Date of the last song post', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0, help_text='Longest streak ever achieved'),
        ),
    ]
